In [21]:
import sys
import numpy as np
from GMM import GaussianMixtureModels


F_BG = 0
F_FG = 1
F_PR_BG = 2
F_PR_FG = 3

gambar = np.array(
[
    [[159, 192, 201], [160, 193, 202], [162, 197, 207], [167, 203, 213], [166, 204, 216], [159, 198, 212], [158, 195, 199]],
    [[159, 192, 201], [156, 192, 200], [159, 194, 204], [163, 201, 213], [162, 201, 215], [152, 193, 208], [135, 177, 190]],
    [[156, 189, 198], [149, 185, 193], [150, 185, 195], [155, 193, 205], [157, 196, 210], [150, 191, 206], [142, 182, 187]],
    [[163, 197, 203], [152, 188, 196], [149, 184, 194], [153, 189, 199], [152, 192, 204], [146, 188, 201], [151, 189, 194]],
    [[150, 187, 191], [158, 195, 199], [160, 196, 202], [151, 189, 194], [145, 182, 190], [143, 182, 191], [145, 184, 198]],
    [[154, 191, 195], [158, 195, 199], [158, 195, 199], [150, 188, 192], [146, 184, 189], [150, 187, 195], [159, 194, 204]],
    [[151, 189, 194], [152, 190, 195], [149, 187, 192], [142, 182, 187], [142, 181, 189], [147, 186, 194], [132, 171, 186]],
    [[150, 187, 195], [146, 185, 193], [143, 182, 190], [141, 180, 188], [143, 182, 190], [147, 186, 195], [144, 185, 194]],
    [[150, 189, 198], [146, 187, 196], [144, 185, 194], [146, 187, 196], [148, 189, 198], [148, 188, 200], [152, 193, 208]],
    [[141, 180, 194], [140, 180, 192], [141, 180, 194], [145, 185, 197], [145, 184, 198], [142, 182, 194], [153, 189, 199]]
]
)

rows, cols, _= gambar.shape
komponen_piksel = np.zeros((rows,cols), dtype=np.uint32)
mask = np.zeros(gambar.shape[:2], dtype=np.uint8)
# gc = GrabCut(gambar, mask)
# ix, iy, x, y = 176, 47, 351, 189
mask[3:8, 2:6] = 1

gc_source = 0
gc_sink = (cols * rows)

print(gc_sink, gc_source)
print('data gambar: ', gambar.shape)
print('mask: ', mask)

70 0
data gambar:  (10, 7, 3)
mask:  [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 1 0]
 [0 0 1 1 1 1 0]
 [0 0 1 1 1 1 0]
 [0 0 1 1 1 1 0]
 [0 0 1 1 1 1 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [27]:
pr_indexes = np.where(np.logical_or(mask.reshape(-1) == F_PR_BG, mask.reshape(-1) == F_PR_FG))
bgd_indexes = np.where(mask.reshape(-1) == F_BG)
fgd_indexes = np.where(mask.reshape(-1) == F_FG)

print(pr_indexes[0].size)
print(bgd_indexes[0].size)
print(fgd_indexes[0].size)

edges = []
edges2 = []

edges.extend(list(zip([gc_source] * pr_indexes[0].size, pr_indexes[0])))
edges.extend(list(zip([gc_source] * bgd_indexes[0].size, bgd_indexes[0])))
edges.extend(list(zip([gc_source] * fgd_indexes[0].size, fgd_indexes[0])))

edges2.extend(list(zip([gc_source] * pr_indexes[0].size, pr_indexes[0])))
edges2.extend(list(zip([gc_source] * bgd_indexes[0].size, bgd_indexes[0])))
edges2.extend(list(zip([gc_source] * fgd_indexes[0].size, fgd_indexes[0])))

print(edges)
print(edges2)

# print(gambar.reshape(-1,3))


0
50
20
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (0, 16), (0, 17), (0, 18), (0, 19), (0, 20), (0, 21), (0, 22), (0, 27), (0, 28), (0, 29), (0, 34), (0, 35), (0, 36), (0, 41), (0, 42), (0, 43), (0, 48), (0, 49), (0, 50), (0, 55), (0, 56), (0, 57), (0, 58), (0, 59), (0, 60), (0, 61), (0, 62), (0, 63), (0, 64), (0, 65), (0, 66), (0, 67), (0, 68), (0, 69), (0, 23), (0, 24), (0, 25), (0, 26), (0, 30), (0, 31), (0, 32), (0, 33), (0, 37), (0, 38), (0, 39), (0, 40), (0, 44), (0, 45), (0, 46), (0, 47), (0, 51), (0, 52), (0, 53), (0, 54)]
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (0, 16), (0, 17), (0, 18), (0, 19), (0, 20), (0, 21), (0, 22), (0, 27), (0, 28), (0, 29), (0, 34), (0, 35), (0, 36), (0, 41), (0, 42), (0, 43), (0, 48), (0, 49), (0, 50), (0, 55), (0, 56), (0, 57), (0, 58), (0, 59), (0, 60), (0, 61), (0

In [ ]:
def inisiasi_piksel():
    s_x, s_y, x, y = 1, 3, 5, 8
    mask[s_y:y, s_x:x] = F_PR_FG
    print(gambar.shape)
    print(mask)

    bg_idx = np.where(np.logical_or(
        mask == F_BG, mask == F_PR_BG
    ))

    fg_idx = np.where(np.logical_or(
        mask == F_FG, mask == F_PR_FG
    ))
    
    # print('(pr_)bgd count: \n', bg_idx, '\n(pr_)fgd count: \n', fg_idx)
    print('(pr_)bgd count: ', bg_idx[1].size, '(pr_)fgd count:', fg_idx[1].size)

    print('inisiasi piksel selesai')

    return(bg_idx, fg_idx)


idx_bg, idx_fg = inisiasi_piksel()


In [ ]:
print(idx_fg)

def init_assign_gmm():
    gmm_fg = GaussianMixtureModels(gambar[idx_fg])
    gmm_bg = GaussianMixtureModels(gambar[idx_bg])

    komponen_piksel[idx_fg] = gmm_fg.assign_component(gambar[idx_fg])
    komponen_piksel[idx_bg] = gmm_bg.assign_component(gambar[idx_bg])

    # gmm_bg = GaussianMixtureModels(gambar[idx_bg])
    print('Komponen piksel FG: %d, Komponen piksel BG: %d, Total komponen: %d' % (len(komponen_piksel[idx_fg]), len(komponen_piksel[idx_bg]), len(komponen_piksel)))
    print('inisiasi GMM selesai')

init_assign_gmm()

In [ ]:
import numpy as np

# Assuming arr is your 3D array with shape (m, n, p)
# Create a sample 3D array for demonstration
# arr = np.random.rand(3, 4)
a = np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]]) 

# Sum along the second axis (axis=1) to add every column
result = np.sum(a, axis=1)

# Print the shapes before and after the sum
print("Original array shape:", a.shape)
print("Result array shape:", result)


In [4]:
import numpy as np

a = np.array([2.0, 3.0, 4.0])
b = np.array([5.0, 6.0, 7.0])

result = -np.log(a) - np.log(b)
result1 = -np.log(np.multiply(a, b))

print(result)
print(result1)


[-2.30258509 -2.89037176 -3.33220451]
[-2.30258509 -2.89037176 -3.33220451]


In [26]:
c = [34] * 43

print(c)

[34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34]
