In [13]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
import random
import igraph as ig


# Cara menghitung means
# uni_labels = [0, 1, 2, 3, 4]
labels = np.array([random.randint(0, 4) for i in range(14)])
uni_labels, count = np.unique(labels, return_counts=True)
means = np.zeros((5, 3))
n_samples = np.zeros(5)
X = np.array([
    [21,39,64], 
    [23,45,11], 
    [23,15,22], 
    [10,56,77],
    [34,80,22],
    [23,15,22], 
    [10,56,77],
    [34,80,22],
    [23,15,22],
    [10,56,77],
    [10,56,77],
    [34,80,22],
    [31,20,12],
    [13,75,42]])
print(means, '\n')
print(X, '\n')
print(labels, '\n')
print(uni_labels, '\n')
# print(means)
for ci in uni_labels:
    n = n_samples[ci]
    print('filter ci: ', X[ci == labels])
    # print(ci)
    # coefs[ci] = n / np.sum(n_samples)
    means[ci] = np.mean(X[ci == labels], axis=0)
    print('mean ci: ', means[ci])
    # covariances[ci] = 0 if n_samples[ci] <= 1 else np.cov(
    #     X[ci == labels].T)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[21 39 64]
 [23 45 11]
 [23 15 22]
 [10 56 77]
 [34 80 22]
 [23 15 22]
 [10 56 77]
 [34 80 22]
 [23 15 22]
 [10 56 77]
 [10 56 77]
 [34 80 22]
 [31 20 12]
 [13 75 42]] 

[2 0 3 1 1 2 2 1 2 3 0 1 2 4] 

[0 1 2 3 4] 

filter ci:  [[23 45 11]
 [10 56 77]]
mean ci:  [16.5 50.5 44. ]
filter ci:  [[10 56 77]
 [34 80 22]
 [34 80 22]
 [34 80 22]]
mean ci:  [28.   74.   35.75]
filter ci:  [[21 39 64]
 [23 15 22]
 [10 56 77]
 [23 15 22]
 [31 20 12]]
mean ci:  [21.6 29.  39.4]
filter ci:  [[23 15 22]
 [10 56 77]]
mean ci:  [16.5 35.5 49.5]
filter ci:  [[13 75 42]]
mean ci:  [13. 75. 42.]


In [14]:
import numpy as np
import random

# Cara menghitung coefs
# uni_labels = [0, 1, 2, 3, 4]
coefs = np.zeros(5)
n_samples = np.zeros(5)

labels = np.array([random.randint(0, 4) for i in range(14)])
uni_labels, count = np.unique(labels, return_counts=True)

n_samples[uni_labels] = count
X = np.array([
    [21,39,64], 
    [23,45,11], 
    [23,15,22], 
    [10,56,77],
    [34,80,22],
    [23,15,22], 
    [10,56,77],
    [34,80,22],
    [23,15,22],
    [10,56,77],
    [10,56,77],
    [34,80,22],
    [31,20,12],
    [13,75,42]])

print(X, '\n')
print(labels, '\n')
print(uni_labels, '\n')
print(n_samples, '\n')

for ci in uni_labels:
    n = n_samples[ci]
    coefs[ci] = n / np.sum(n_samples)
    print(n)
    print(coefs[ci],'\n')

    

[[21 39 64]
 [23 45 11]
 [23 15 22]
 [10 56 77]
 [34 80 22]
 [23 15 22]
 [10 56 77]
 [34 80 22]
 [23 15 22]
 [10 56 77]
 [10 56 77]
 [34 80 22]
 [31 20 12]
 [13 75 42]] 

[3 2 1 1 3 1 2 0 2 3 4 4 1 3] 

[0 1 2 3 4] 

[1. 4. 3. 4. 2.] 

1.0
0.07142857142857142 

4.0
0.2857142857142857 

3.0
0.21428571428571427 

4.0
0.2857142857142857 

2.0
0.14285714285714285 



In [15]:
# import numpy as np
# import random

# # Cara menghitung coefs
# # uni_labels = [0, 1, 2, 3, 4]
# coefs = np.zeros(5)
# n_samples = np.zeros(5)
# covariances = np.zeros((5, 3, 3))


# labels = np.array([random.randint(0, 4) for i in range(14)])
# uni_labels, count = np.unique(labels, return_counts=True)

# n_samples[uni_labels] = count
# X = np.array([
#     [21,39,64], 
#     [23,45,11], 
#     [23,15,22], 
#     [10,56,77],
#     [34,80,22],
#     [23,15,22], 
#     [10,56,77],
#     [34,80,22],
#     [23,15,22],
#     [10,56,77],
#     [10,56,77],
#     [34,80,22],
#     [31,20,12],
#     [13,75,42]])

# print(X, '\n')
# print(labels, '\n')
# print(uni_labels, '\n')
# print(n_samples, '\n')

# for ci in uni_labels:
#     n = n_samples[ci]
#     covariances[ci] = 0 if n_samples[ci] <= 1 else np.cov(X[ci == labels].T)

#     print(n)
#     print(covariances[ci],'\n')
#     np.linalg.inv(covariances[ci])

    

In [16]:
class Graph:
    def __init__(self, num_nodes):
        self.num_nodes = num_nodes
        self.adj_list = [[] for _ in range(num_nodes)]

    def add_edge(self, u, v):
        self.adj_list[u].append(v)
        # self.adj_list[v].append(u)

    def get_edges(self):
        edges = []
        for u in range(self.num_nodes):
            for v in self.adj_list[u]:
                edges.append((u, v))
        return edges

    def print_graph(self):
        for u in range(self.num_nodes):
            print(f"Node {u} is connected to: {self.adj_list[u]}")

# # Example usage
# if __name__ == "__main__":
#     num_nodes = 5
#     graph = Graph(num_nodes)

#     # Adding edges to the graph
#     graph.add_edge(3, 0)    
#     graph.add_edge(3, 1)
#     graph.add_edge(3, 2)
#     graph.add_edge(3, 3)
#     graph.add_edge(3, 4)
#     graph.add_edge(4, 0)
#     graph.add_edge(4, 1)
#     graph.add_edge(4, 2)
#     graph.add_edge(4, 3)
#     graph.add_edge(4, 4)

#     # Print the edges as a list of tuples
#     edges = graph.get_edges()
#     print("Edges of the graph:")
#     print(edges)

#     graph.print_graph()


In [17]:
import sys
import numpy as np
import cv2 as cv
import igraph as ig



DRAW_BG = {'val': 0}
DRAW_FG = {'val': 1}
DRAW_PR_BG = {'val': 2}
DRAW_PR_FG = {'val': 3}



img = np.array(
[
 [[159, 192, 201], [160, 193, 202], [162, 197, 207], [167, 203, 213], [166, 204, 216], [159, 198, 212]],
 [[159, 192, 201], [156, 192, 200], [159, 194, 204], [163, 201, 213], [162, 201, 215], [152, 193, 208]],
 [[156, 189, 198], [149, 185, 193], [150, 185, 195], [155, 193, 205], [157, 196, 210], [150, 191, 206]],
 [[163, 197, 203], [152, 188, 196], [149, 184, 194], [153, 189, 199], [152, 192, 204], [146, 188, 201]],
 [[150, 187, 191], [158, 195, 199], [160, 196, 202], [151, 189, 194], [145, 182, 190], [143, 182, 191]],
 [[154, 191, 195], [158, 195, 199], [158, 195, 199], [150, 188, 192], [146, 184, 189], [150, 187, 195]],
 [[151, 189, 194], [152, 190, 195], [149, 187, 192], [142, 182, 187], [142, 181, 189], [147, 186, 194]],
 [[150, 187, 195], [146, 185, 193], [143, 182, 190], [141, 180, 188], [143, 182, 190], [147, 186, 195]],
 [[150, 189, 198], [146, 187, 196], [144, 185, 194], [146, 187, 196], [148, 189, 198], [148, 188, 200]],
 [[141, 180, 194], [140, 180, 192], [141, 180, 194], [145, 185, 197], [145, 184, 198], [142, 182, 194]],
 [[130, 171, 186], [129, 171, 184], [132, 173, 188], [135, 177, 190], [136, 175, 190], [133, 172, 186]],
 [[127, 170, 185], [126, 169, 184], [130, 171, 186], [133, 174, 189], [133, 172, 187], [132, 171, 186]]
]
)

rows, cols, _= img.shape
comp_idxs = np.zeros((rows,cols), dtype=np.uint32)
mask = np.zeros(img.shape[:2], dtype=np.uint8)  # mask initialized to PR_BG
bgd_gmm = None
fgd_gmm = None
gc_graph = None


mask[2:9,1:4] = DRAW_PR_FG['val']

print(mask)

bgd_indexes = np.where(mask.reshape(-1) == DRAW_BG['val'])
fgd_indexes = np.where(mask.reshape(-1) == DRAW_FG['val'])
pr_indexes = np.where(np.logical_or(mask.reshape(-1) == DRAW_PR_BG['val'], mask.reshape(-1) == DRAW_PR_FG['val']))
print(pr_indexes)
pr_indexes = np.where(np.logical_or(mask == DRAW_PR_BG['val'], mask == DRAW_PR_FG['val']))
print(pr_indexes)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
(array([13, 14, 15, 19, 20, 21, 25, 26, 27, 31, 32, 33, 37, 38, 39, 43, 44,
       45, 49, 50, 51], dtype=int64),)
(array([2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8],
      dtype=int64), array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
      dtype=int64))


In [18]:
edges = []
gc_graph_capacity = []
gc_graph = None
gc_graph_capacity = None           # Edge capacities
gc_source = img.shape[0] * img.shape[1]  # "object" terminal S
gc_sink = gc_source + 1       # "background" terminal T


# print('TB count: %d, TF count: %d, TU count: %d' % (
#     len(bgd_indexes[0]), len(fgd_indexes[0]), len(pr_indexes[0])))
print(img.shape)
print('mask now: \n', mask)
# print('BG count:', bgd_indexes)
# print('FG count:', fgd_indexes)
print('PR count:', len(pr_indexes[0]))
print([9] * pr_indexes[0].size)
# edges.extend(list(zip([gc_source] * pr_indexes[0].size, pr_indexes[0])))
# _D = -np.log(bgd_gmm.calc_prob(img.reshape(-1, 3)[pr_indexes]))
# gc_graph_capacity.extend(_D.tolist())


# edges.extend(list(zip([gc_sink] * pr_indexes[0].size, pr_indexes[0])))
# _D = -np.log(fgd_gmm.calc_prob(img.reshape(-1, 3)[pr_indexes]))
# gc_graph_capacity.extend(_D.tolist())


# edges.extend(list(zip([gc_source] * bgd_indexes[0].size, bgd_indexes[0])))
# edges.extend(list(zip([gc_sink] * bgd_indexes[0].size, bgd_indexes[0])))

# edges.extend(list(zip([gc_source] * fgd_indexes[0].size, fgd_indexes[0])))
# edges.extend(list(zip([gc_sink] * fgd_indexes[0].size, fgd_indexes[0])))


num_nodes = (rows * cols) + 2
graph = Graph(num_nodes)

for i in pr_indexes[0]:
    graph.add_edge(gc_source, i)

for i in pr_indexes[0]:
    graph.add_edge(gc_sink, i)

# for i in bgd_indexes[0]:
#     graph.add_edge(gc_source, i)

# for i in bgd_indexes[0]:
#     graph.add_edge(gc_sink, i)

# for i in fgd_indexes[0]:
#     graph.add_edge(gc_source, i)

# for i in fgd_indexes[0]:
#     graph.add_edge(gc_sink, i)


edges2 = graph.get_edges()
print("Edges of the graph:")
print(edges2)
    
print(edges)
# print(gc_graph_capacity)


gc_graph = ig.Graph((cols * rows + 2), edges)
# gc_graph.add_edges()

print('gc_graph: ', gc_graph)

(12, 6, 3)
mask now: 
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 3 3 3 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
PR count: 21
[9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
Edges of the graph:
[(72, 2), (72, 2), (72, 2), (72, 3), (72, 3), (72, 3), (72, 4), (72, 4), (72, 4), (72, 5), (72, 5), (72, 5), (72, 6), (72, 6), (72, 6), (72, 7), (72, 7), (72, 7), (72, 8), (72, 8), (72, 8), (73, 2), (73, 2), (73, 2), (73, 3), (73, 3), (73, 3), (73, 4), (73, 4), (73, 4), (73, 5), (73, 5), (73, 5), (73, 6), (73, 6), (73, 6), (73, 7), (73, 7), (73, 7), (73, 8), (73, 8), (73, 8)]
[]
gc_graph:  IGRAPH U--- 74 0 --


In [19]:
class Graph:
    def __init__(self, vertices):
        self.V = vertices
        self.graph = {}

    def add_edge(self, u, v, capacity):
        if u not in self.graph:
            self.graph[u] = {}
        if v not in self.graph:
            self.graph[v] = {}
        self.graph[u][v] = capacity
        self.graph[v][u] = 0

    # Find the minimum capacity edge in the augmenting path
    def find_path_capacity(self, parent, source, sink):
        path_capacity = float("inf")
        v = sink
        while v != source:
            u = parent[v]
            path_capacity = min(path_capacity, self.graph[u][v])
            v = u
        return path_capacity

    # Use Depth-First Search to find an augmenting path
    def dfs(self, u, sink, visited, parent):
        visited[u] = True
        if u == sink:
            return True
        if u in self.graph:
            for v in self.graph[u]:
                if not visited[v] and self.graph[u][v] > 0:
                    parent[v] = u
                    if self.dfs(v, sink, visited, parent):
                        return True
        return False

    # Function to perform DFS from the source vertex to find the partition
    def find_partition(self, u, visited, partition):
        visited[u] = True
        partition.append(u)
        if u in self.graph:
            for v in self.graph[u]:
                if not visited[v] and self.graph[u][v] > 0:
                    self.find_partition(v, visited, partition)

    # Ford-Fulkerson algorithm to find the min-cut and the partition
    def ford_fulkerson(self, source, sink):
        # ... (the previous implementation remains the same)

        partition_foreground = []
        visited = [False] * self.V

        # Find the vertices in the foreground partition by DFS from the source
        self.find_partition(source, visited, partition_foreground)

        # All the remaining vertices (not in the foreground) are in the background partition
        partition_background = [v for v in range(self.V) if not visited[v]]

        return max_flow, partition_foreground, partition_background

# Example usage:
if __name__ == "__main__":
    g = Graph(6)
    g.add_edge(0, 1, 16)
    g.add_edge(0, 2, 13)
    g.add_edge(1, 2, 10)
    g.add_edge(1, 3, 12)
    g.add_edge(2, 1, 4)
    g.add_edge(2, 4, 14)
    g.add_edge(3, 2, 9)
    g.add_edge(3, 5, 20)
    g.add_edge(4, 3, 7)
    g.add_edge(4, 5, 4)

    source = 0
    sink = 5

    mincut, foreground_partition, background_partition = g.ford_fulkerson(source, sink)
    print("Min-cut value:", mincut)
    print("Foreground partition:", foreground_partition)
    print("Background partition:", background_partition)

NameError: name 'max_flow' is not defined