In [314]:
import sys
import numpy as np
import igraph as ig


F_BG = 0
F_FG = 1
F_PR_BG = 2
F_PR_FG = 3

gambar = np.array(
[
    [[159, 192, 201], [160, 193, 202], [162, 197, 207], [167, 203, 213], [166, 204, 216]],
    [[159, 192, 201], [156, 192, 200], [159, 194, 204], [163, 201, 213], [162, 201, 215]],
    [[156, 189, 198], [149, 185, 193], [150, 185, 195], [155, 193, 205], [157, 196, 210]],
    [[163, 197, 203], [152, 188, 196], [149, 184, 194], [153, 189, 199], [152, 192, 204]],
    [[150, 187, 191], [158, 195, 199], [160, 196, 202], [151, 189, 194], [145, 182, 190]],
    [[154, 191, 195], [158, 195, 199], [158, 195, 199], [150, 188, 192], [146, 184, 189]],
    [[151, 189, 194], [152, 190, 195], [149, 187, 192], [142, 182, 187], [142, 181, 189]],
]
)

# gambar = np.array([
#     [[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128], [128, 128, 0], [128, 0, 128], [0, 128, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[128, 255, 255], [192, 192, 192], [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 0, 0], [0, 128, 0], [0, 0, 128], [128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255]],
#     [[128, 255, 255], [192, 192, 192], [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[128, 255, 255], [192, 192, 192], [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 255, 255], [192, 192, 192], [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
# ], dtype=np.uint8)

rows, cols, _= gambar.shape
komponen_piksel = np.zeros((rows,cols), dtype=np.uint32)
mask = np.zeros(gambar.shape[:2], dtype=np.uint8)
mask[2:6, 1:4] = F_PR_FG

gc_source = 0
gc_sink = (cols * rows)

print(gc_sink, gc_source)
print('data gambar: ', gambar.shape)
print('mask: \n', mask)

35 0
data gambar:  (7, 5, 3)
mask: 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 3 3 3 0]
 [0 3 3 3 0]
 [0 3 3 3 0]
 [0 3 3 3 0]
 [0 0 0 0 0]]


In [315]:
import random

pr_indexes = np.where(np.logical_or(mask.reshape(-1) == F_PR_BG, mask.reshape(-1) == F_PR_FG))
bgd_indexes = np.where(mask.reshape(-1) == F_BG)
fgd_indexes = np.where(mask.reshape(-1) == F_FG)

print('TB count: %d, TF count: %d, TU count: %d' % (len(bgd_indexes[0]), len(fgd_indexes[0]), len(pr_indexes[0])))
print("\n")

edges = []
# capacities = []

U_count_fg = [random.uniform(0, 1) for _ in range(len(pr_indexes[0]))]
U_count_bg = [random.uniform(0, 1) for _ in range(len(pr_indexes[0]))]

print(U_count_fg)
print(U_count_bg)

edges.extend(list(zip([gc_source] * bgd_indexes[0].size, bgd_indexes[0])))
# capacities.extend([0] * bgd_indexes[0].size)
print(edges)
print(len(edges))

edges.extend(list(zip([gc_source] * pr_indexes[0].size, pr_indexes[0])))
# capacities.extend(U_count_bg)

print(edges)
print(len(edges))

edges.extend(list(zip([gc_source] * fgd_indexes[0].size, fgd_indexes[0])))
# capacities.extend([9 * 50] * fgd_indexes[0].size)
print(edges)
print(len(edges))

edges.extend(list(zip([gc_sink] * bgd_indexes[0].size, bgd_indexes[0])))
# capacities.extend([9 * 50] * bgd_indexes[0].size)
print(edges)
print(len(edges))

edges.extend(list(zip([gc_sink] * pr_indexes[0].size, pr_indexes[0])))
# capacities.extend(U_count_fg)
print(len(edges))

edges.extend(list(zip([gc_sink] * fgd_indexes[0].size, fgd_indexes[0])))
# capacities.extend([0] * fgd_indexes[0].size)
print(edges)
print(len(edges))

print('\n')

capacities = [random.randint(0, 30) for _ in range(len(edges))]
print('cap: ', capacities)

print('edges: ',edges)


TB count: 23, TF count: 0, TU count: 12


[0.8703182034787209, 0.5157193222460503, 0.7861246005108321, 0.19342280471313567, 0.4344031080187246, 0.8866483712926598, 0.30296933546345717, 0.872299555007351, 0.26326400759663593, 0.3672906895320044, 0.9265418971931235, 0.21405834825080028]
[0.9628533467637457, 0.07485879786630112, 0.04794670995661432, 0.5933421863517468, 0.7973340547498362, 0.8410113239076237, 0.6075453347886586, 0.21300121077776923, 0.03373915862253207, 0.5449184962370001, 0.8266881398009929, 0.18144263618633472]
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 14), (0, 15), (0, 19), (0, 20), (0, 24), (0, 25), (0, 29), (0, 30), (0, 31), (0, 32), (0, 33), (0, 34)]
23
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 14), (0, 15), (0, 19), (0, 20), (0, 24), (0, 25), (0, 29), (0, 30), (0, 31), (0, 32), (0, 33), (0, 34), (0, 11), (0, 12), (0, 13), (0, 16), (0, 17), (0, 18), (0, 21), (0, 22

In [316]:
import random

graph = ig.Graph(rows*cols + 1)
graph.add_edges(edges)

# Add edges dynamically, which will add vertices as needed

graph.es['weight'] = np.zeros(len(edges))
graph.es['weight'] = capacities

# Displaying information about edges
print("Information about edges:")

# for edge in graph.es:
#     # print(edge.index)
#     print(f"Edge {edge.index}: Source = {edge.source}, Target = {edge.target}, Capacity = {edge['capacity']}")

# print(graph.es['weight'][0])

Information about edges:


In [317]:
from igraph import Graph

def stoer_wagner(graph):
    n = graph.vcount()
    print(n)
    min_cut_weight = float('inf')

    while n > 1:

        # Phases 2 & 3: Contract and find the minimum cut
        # Phase 1: Initialize the cut
        cut = [False] * n
        # Choose an arbitrary vertex
        source = 0
        for _ in range(n - 1):
            # Mark the source vertex as part of the cut

            # Find the minimum cut between the cut and the rest of the graph
            min_cut_value = float('inf')
            contracted_vertex = -1
            cut[source] = True

            for v in range(n):
                if not cut[v]:
                    cut_value = 0

                    # Sum the weights of edges from the cut to the rest of the graph
                    for edge in graph.es:
                        if (edge.source == v and cut[edge.target]) or (edge.target == v and cut[edge.source]):
                            cut_value += edge["weight"]

                    # Update the minimum cut value
                    if cut_value < min_cut_value:
                        min_cut_value = cut_value
                        contracted_vertex = v

            # Contract the graph by merging the source and the contracted vertex
            contracted_vertices = [source, contracted_vertex]
            graph.add_vertex()
            new_vertex = n  # Index of the newly added vertex
            for v in contracted_vertices:
                for neighbor in graph.neighbors(v):
                    if neighbor not in contracted_vertices:
                        graph.add_edge(new_vertex, neighbor, weight=graph[v, neighbor])

            graph.delete_vertices(contracted_vertices)

            # Update the number of vertices
            n -= 1

        # Update the minimum cut weight
        # print(min_cut_weight)
        # print(min_cut_value)
        min_cut_weight = min(min_cut_weight, min_cut_value)

    return min_cut_weight

min_cut_weight = stoer_wagner(graph)
print("Minimum Cut Weight:", min_cut_weight)


36
Minimum Cut Weight: 240


In [318]:
node_a = graph.vs[0]
n_nodes = graph.vcount()
all_nodes = np.array(graph.vs)
best_cut = []
best_value = float('inf')
cut_weight = int
node_pq = []
in_pq = []

# for i in graph.vs:
#     print(i)

print(all_nodes[n_nodes-1])
node_a == all_nodes[1]

# print(graph.vs[0].index)


igraph.Vertex(<igraph.Graph object at 0x000002B241EAE340>, 0, {})


IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
while (n_nodes >= 2):
    # Phase 5 from paper
    # Phase 6 from paper
    # if (all_nodes[n_nodes-1] != node_a):
    #     node_pq.append(0)
    #     in_pq.append(True)
    # print(n_nodes)
    nodes_to_add = set(all_nodes) - {node_a}

    node_pq.extend([0] * len(nodes_to_add))
    in_pq.extend(True for _ in nodes_to_add)

    n_nodes -= 1

print(len(nodes_to_add))

In [ ]:
# # Running the mincut algorithm
# mincut = graph.st_mincut(gc_source, gc_sink, capacities)

# print('foreground pixels: ', mincut.partition[0], "len: ", len(mincut.partition[0]))
# print('background pixels: ', mincut.partition[1], "len: ", len(mincut.partition[1]))

# idx_pr = np.where(np.logical_or(mask == F_PR_FG, mask == F_PR_BG))
# print(idx_pr)

# img_indexes = np.arange(rows * cols, dtype=np.uint32).reshape(rows, cols)
# print('mask: \n', mask)

# mask[idx_pr] = np.where(np.isin(img_indexes[idx_pr], mincut.partition[0]),F_PR_FG, F_PR_BG)
# idx_pr = np.where(np.logical_or(mask == F_PR_FG, mask == F_PR_BG))
# print(len(idx_pr[0]))

# mask = np.where((mask == F_FG) | (mask == F_PR_FG), 255, 0).astype('uint8')
# print('mask: \n', mask)


In [331]:
from igraph import Graph

def stoer_wagner(graph):
    n = graph.vcount()
    print(n)
    min_cut_weight = float('inf')

    while n > 1:

        # Phases 2 & 3: Contract and find the minimum cut
        # Phase 1: Initialize the cut
        cut = [False] * n
        # Choose an arbitrary vertex
        source = 0
        for _ in range(n - 1):

            # Find the minimum cut between the cut and the rest of the graph
            min_cut_value = float('inf')
            contracted_vertex = -1

            for v in range(n):
                if not cut[v]:
                    cut_value = 0
                    # Mark the source vertex as part of the cut
                    cut[source] = True

                    # Sum the weights of edges from the cut to the rest of the graph
                    for edge in graph.es:
                        if (edge.source == v and cut[edge.target]) or (edge.target == v and cut[edge.source]):
                            cut_value += edge["weight"]

                    # Update the minimum cut value
                    if cut_value < min_cut_value:
                        min_cut_value = cut_value
                        contracted_vertex = v

            # Contract the graph by merging the source and the contracted vertex
            contracted_vertices = [source, contracted_vertex]
            graph.add_vertex()
            new_vertex = n  # Index of the newly added vertex
            for v in contracted_vertices:
                for neighbor in graph.neighbors(v):
                    if neighbor not in contracted_vertices:
                        graph.add_edge(new_vertex, neighbor, weight=graph[v, neighbor])

            graph.delete_vertices(contracted_vertices)

            # Update the number of vertices
            n -= 1

        # Update the minimum cut weight
        # print(min_cut_weight)
        # print(min_cut_value)
        min_cut_weight = min(min_cut_weight, min_cut_value)

    return min_cut_weight

# Example usage:
edges = [(0, 1), (1, 2), (2, 0), (1, 3), (3, 4), (4, 1)]
weights = [4, 1, 24, 9, 18, 12] 
graph = Graph(edges=edges, directed=False)
graph.es["weight"] = weights

min_cut_weight = stoer_wagner(graph)
print("Minimum Cut Weight:", min_cut_weight)


5


IndexError: list index out of range

In [ ]:
from igraph import Graph

def stoer_wagner(graph):
    n = graph.vcount()
    min_cut_weight = float('inf')
    min_cut_nodes = []

    while n > 1:
        # Phase 1: Initialize the cut
        cut = [False] * n
        # Choose an arbitrary vertex
        source = 0

        # Phases 2 & 3: Contract and find the minimum cut
        contracted_vertices = set()

        for _ in range(n - 1):
            # Mark the source vertex as part of the cut
            cut[source] = True

            # Find the minimum cut between the cut and the rest of the graph
            min_cut_value = float('inf')
            contracted_vertex = -1

            for v in range(n):
                if not cut[v]:
                    cut_value = 0

                    # Sum the weights of edges from the cut to the rest of the graph
                    for edge in graph.es:
                        if (edge.source == v and cut[edge.target]) or (edge.target == v and cut[edge.source]):
                            cut_value += edge["weight"]

                    # Update the minimum cut value
                    if cut_value < min_cut_value:
                        min_cut_value = cut_value
                        contracted_vertex = v

            # Update the cut list
            cut[contracted_vertex] = True

            # Mark the contracted vertices for deletion
            contracted_vertices.add(contracted_vertex)

            # Create a new graph for contracted vertices
            contracted_graph = Graph(directed=False)
            for v in range(n):
                if not cut[v]:
                    contracted_graph.add_vertex()

            for edge in graph.es:
                if not cut[edge.source] and not cut[edge.target]:
                    contracted_graph.add_edge(edge.source, edge.target, weight=edge["weight"])

            # Merge the source and contracted vertex into a new vertex
            contracted_graph.add_edge(n, contracted_vertex, weight=0)

            # Replace the original graph with the contracted graph
            graph = contracted_graph
            n = graph.vcount()

        # Update the minimum cut weight and nodes
        if min_cut_value < min_cut_weight:
            min_cut_weight = min_cut_value
            min_cut_nodes = [i for i, cut_flag in enumerate(cut) if cut_flag]

    return min_cut_weight, min_cut_nodes

# Example usage:
edges = [(0, 1), (1, 2), (2, 0), (1, 3), (3, 4), (4, 1)]
weights = [2, 1, 3, 4, 5, 6]  # Independent weights for edges
graph = Graph(6)
graph.add_edges(edges)
graph.es["weight"] = weights

min_cut_weight, min_cut_nodes = stoer_wagner(graph)
print("Minimum Cut Weight:", min_cut_weight)
print("Nodes in Minimum Cut:", min_cut_nodes)


InternalError: Error at src/graph/type_indexededgelist.c:261: Out-of-range vertex IDs when adding edges. -- Invalid vertex ID