In [57]:
import sys
import numpy as np
import igraph as ig


F_BG = 0
F_FG = 1
F_PR_BG = 2
F_PR_FG = 3

gambar = np.array(
[
    [[159, 192, 201], [160, 193, 202], [162, 197, 207], [167, 203, 213], [166, 204, 216]],
    [[159, 192, 201], [156, 192, 200], [159, 194, 204], [163, 201, 213], [162, 201, 215]],
    [[156, 189, 198], [149, 185, 193], [150, 185, 195], [155, 193, 205], [157, 196, 210]],
    [[163, 197, 203], [152, 188, 196], [149, 184, 194], [153, 189, 199], [152, 192, 204]],
    [[150, 187, 191], [158, 195, 199], [160, 196, 202], [151, 189, 194], [145, 182, 190]],
    [[154, 191, 195], [158, 195, 199], [158, 195, 199], [150, 188, 192], [146, 184, 189]],
    [[151, 189, 194], [152, 190, 195], [149, 187, 192], [142, 182, 187], [142, 181, 189]],
]
)

# gambar = np.array([
#     [[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128], [128, 128, 0], [128, 0, 128], [0, 128, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[128, 255, 255], [192, 192, 192], [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 0, 0], [0, 128, 0], [0, 0, 128], [128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255]],
#     [[128, 255, 255], [192, 192, 192], [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[128, 255, 255], [192, 192, 192], [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 255, 255], [192, 192, 192], [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128]],
#     [[255, 128, 0], [255, 255, 255], [128, 128, 128], [0, 0, 0], [255, 128, 128], [128, 255, 128], [128, 128, 255], [255, 255, 128], [255, 128, 255], [128, 255, 255], [192, 192, 192], [0, 128, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
#     [[128, 128, 0], [0, 128, 128], [128, 0, 128], [255, 128, 192], [192, 255, 128], [192, 128, 255], [255, 192, 128], [255, 192, 255], [192, 255, 192], [192, 192, 255], [255, 255, 192], [255, 192, 128]],
# ], dtype=np.uint8)

rows, cols, _= gambar.shape
komponen_piksel = np.zeros((rows,cols), dtype=np.uint32)
mask = np.zeros(gambar.shape[:2], dtype=np.uint8)
mask[2:6, 1:4] = F_PR_FG

gc_source = 0
gc_sink = (cols * rows)

print(gc_sink, gc_source)
print('data gambar: ', gambar.shape)
print('mask: \n', mask)

35 0
data gambar:  (7, 5, 3)
mask: 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 3 3 3 0]
 [0 3 3 3 0]
 [0 3 3 3 0]
 [0 3 3 3 0]
 [0 0 0 0 0]]


In [58]:
import random

pr_indexes = np.where(np.logical_or(mask.reshape(-1) == F_PR_BG, mask.reshape(-1) == F_PR_FG))
bgd_indexes = np.where(mask.reshape(-1) == F_BG)
fgd_indexes = np.where(mask.reshape(-1) == F_FG)

print('TB count: %d, TF count: %d, TU count: %d' % (len(bgd_indexes[0]), len(fgd_indexes[0]), len(pr_indexes[0])))
print("\n")

edges = []
# capacities = []

U_count_fg = [random.uniform(0, 1) for _ in range(len(pr_indexes[0]))]
U_count_bg = [random.uniform(0, 1) for _ in range(len(pr_indexes[0]))]

print(U_count_fg)
print(U_count_bg)

edges.extend(list(zip([gc_source] * bgd_indexes[0].size, bgd_indexes[0])))
# capacities.extend([0] * bgd_indexes[0].size)
print(edges)
print(len(edges))

edges.extend(list(zip([gc_source] * pr_indexes[0].size, pr_indexes[0])))
# capacities.extend(U_count_bg)

print(edges)
print(len(edges))

edges.extend(list(zip([gc_source] * fgd_indexes[0].size, fgd_indexes[0])))
# capacities.extend([9 * 50] * fgd_indexes[0].size)
print(edges)
print(len(edges))

edges.extend(list(zip([gc_sink] * bgd_indexes[0].size, bgd_indexes[0])))
# capacities.extend([9 * 50] * bgd_indexes[0].size)
print(edges)
print(len(edges))

edges.extend(list(zip([gc_sink] * pr_indexes[0].size, pr_indexes[0])))
# capacities.extend(U_count_fg)
print(len(edges))

edges.extend(list(zip([gc_sink] * fgd_indexes[0].size, fgd_indexes[0])))
# capacities.extend([0] * fgd_indexes[0].size)
print(edges)
print(len(edges))

print('\n')

capacities = [random.randint(0, 30) for _ in range(len(edges))]
print('cap: ', capacities)

print('edges: ',edges)


TB count: 23, TF count: 0, TU count: 12


[0.3668338496501147, 0.34611380195011177, 0.3671022476429483, 0.0709811311171561, 0.5830337330603428, 0.30799326977466923, 0.9911674979086648, 0.9974719603633545, 0.9365506790775111, 0.905168409079108, 0.3270102563116729, 0.20361943269202354]
[0.407821214586925, 0.7897179980981682, 0.4243930729972548, 0.12063107318123023, 0.6003030933024176, 0.8753079074451359, 0.5904039731583341, 0.11799498861749758, 0.07449946877871383, 0.8970610248435118, 0.4444915569234956, 0.673253531968023]
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 14), (0, 15), (0, 19), (0, 20), (0, 24), (0, 25), (0, 29), (0, 30), (0, 31), (0, 32), (0, 33), (0, 34)]
23
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 14), (0, 15), (0, 19), (0, 20), (0, 24), (0, 25), (0, 29), (0, 30), (0, 31), (0, 32), (0, 33), (0, 34), (0, 11), (0, 12), (0, 13), (0, 16), (0, 17), (0, 18), (0, 21), (0, 22), (0

In [59]:
import random

graph = ig.Graph(rows*cols + 1)
graph.add_edges(edges)

# Add edges dynamically, which will add vertices as needed

graph.es['weight'] = np.zeros(len(edges))
graph.es['weight'] = capacities

# Displaying information about edges
print("Information about edges:")

# for edge in graph.es:
#     # print(edge.index)
#     print(f"Edge {edge.index}: Source = {edge.source}, Target = {edge.target}, Capacity = {edge['capacity']}")

print(graph.es['weight'][0])

Information about edges:
29


In [60]:
node_a = graph.vs[0]
n_nodes = graph.vcount()
all_nodes = np.array(graph.vs)
best_cut = []
best_value = float('inf')
cut_weight = int
node_pq = []
in_pq = []

# for i in graph.vs:
#     print(i)


print(graph.vs[0].index)


0


In [65]:
while (n_nodes >= 2):
    # Phase 5 from paper
    # Phase 6 from paper
    for node in all_nodes:
        if (node != node_a):
            node_pq.append(0)
            in_pq.append(True)
    
    n_nodes -= 1
print(len(node_pq))

1225


In [62]:
# # Running the mincut algorithm
# mincut = graph.st_mincut(gc_source, gc_sink, capacities)

# print('foreground pixels: ', mincut.partition[0], "len: ", len(mincut.partition[0]))
# print('background pixels: ', mincut.partition[1], "len: ", len(mincut.partition[1]))

# idx_pr = np.where(np.logical_or(mask == F_PR_FG, mask == F_PR_BG))
# print(idx_pr)

# img_indexes = np.arange(rows * cols, dtype=np.uint32).reshape(rows, cols)
# print('mask: \n', mask)

# mask[idx_pr] = np.where(np.isin(img_indexes[idx_pr], mincut.partition[0]),F_PR_FG, F_PR_BG)
# idx_pr = np.where(np.logical_or(mask == F_PR_FG, mask == F_PR_BG))
# print(len(idx_pr[0]))

# mask = np.where((mask == F_FG) | (mask == F_PR_FG), 255, 0).astype('uint8')
# print('mask: \n', mask)


In [63]:
import random

# Specify the size of the array
array_size = 10  # Change this to your desired size

# Generate an array of unique random integers within a specified range
random_array = random.sample(range(100), array_size)  # Change the range as needed

# Print the random array
print("Random Array:", random_array)


Random Array: [62, 0, 1, 71, 75, 93, 54, 7, 45, 29]
