In [8]:
import sys
import numpy as np
from GMM import GaussianMixtureModels


F_BG = 0
F_FG = 1
F_PR_BG = 2
F_PR_FG = 3

gambar = np.array(
[
    [[159, 192, 201], [160, 193, 202], [162, 197, 207], [167, 203, 213], [166, 204, 216], [159, 198, 212], [158, 195, 199]],
    [[159, 192, 201], [156, 192, 200], [159, 194, 204], [163, 201, 213], [162, 201, 215], [152, 193, 208], [135, 177, 190]],
    [[156, 189, 198], [149, 185, 193], [150, 185, 195], [155, 193, 205], [157, 196, 210], [150, 191, 206], [142, 182, 187]],
    [[163, 197, 203], [152, 188, 196], [149, 184, 194], [153, 189, 199], [152, 192, 204], [146, 188, 201], [151, 189, 194]],
    [[150, 187, 191], [158, 195, 199], [160, 196, 202], [151, 189, 194], [145, 182, 190], [143, 182, 191], [145, 184, 198]],
    [[154, 191, 195], [158, 195, 199], [158, 195, 199], [150, 188, 192], [146, 184, 189], [150, 187, 195], [159, 194, 204]],
    [[151, 189, 194], [152, 190, 195], [149, 187, 192], [142, 182, 187], [142, 181, 189], [147, 186, 194], [132, 171, 186]],
    [[150, 187, 195], [146, 185, 193], [143, 182, 190], [141, 180, 188], [143, 182, 190], [147, 186, 195], [144, 185, 194]],
    [[150, 189, 198], [146, 187, 196], [144, 185, 194], [146, 187, 196], [148, 189, 198], [148, 188, 200], [152, 193, 208]],
    [[141, 180, 194], [140, 180, 192], [141, 180, 194], [145, 185, 197], [145, 184, 198], [142, 182, 194], [153, 189, 199]]
]
)

rows, cols, _= gambar.shape
komponen_piksel = np.zeros((rows,cols), dtype=np.uint32)
mask = np.zeros(gambar.shape[:2], dtype=np.uint8)
# gc = GrabCut(gambar, mask)
# ix, iy, x, y = 176, 47, 351, 189
# mask[iy:y, ix:x] = 1

gc_source = 0
gc_sink = (cols * rows)

print(gc_sink, gc_source)
print('data gambar: ', gambar.shape)

70 0
data gambar:  (10, 7, 3)


In [9]:
pr_indexes = np.where(np.logical_or(mask.reshape(-1) == F_PR_BG, mask.reshape(-1) == F_PR_FG))
bgd_indexes = np.where(mask.reshape(-1) == F_BG)
fgd_indexes = np.where(mask.reshape(-1) == F_FG)

print(pr_indexes[0])
print(bgd_indexes[0])

edges = []

edges.extend(list(zip([gc_source] * pr_indexes[0].size, pr_indexes[0])))
edges.extend(list(zip([gc_source] * bgd_indexes[0].size, bgd_indexes[0])))
edges.extend(list(zip([gc_source] * fgd_indexes[0].size, fgd_indexes[0])))


print(edges)

print(gambar.reshape(-1,3))


[]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (0, 16), (0, 17), (0, 18), (0, 19), (0, 20), (0, 21), (0, 22), (0, 23), (0, 24), (0, 25), (0, 26), (0, 27), (0, 28), (0, 29), (0, 30), (0, 31), (0, 32), (0, 33), (0, 34), (0, 35), (0, 36), (0, 37), (0, 38), (0, 39), (0, 40), (0, 41), (0, 42), (0, 43), (0, 44), (0, 45), (0, 46), (0, 47), (0, 48), (0, 49), (0, 50), (0, 51), (0, 52), (0, 53), (0, 54), (0, 55), (0, 56), (0, 57), (0, 58), (0, 59), (0, 60), (0, 61), (0, 62), (0, 63), (0, 64), (0, 65), (0, 66), (0, 67), (0, 68), (0, 69)]
[[159 192 201]
 [160 193 202]
 [162 197 207]
 [167 203 213]
 [166 204 216]
 [159 198 212]
 [158 195 199]
 [159 192 201]
 [156 192 200]
 [159 194 204]
 [163 201 21

In [10]:
def inisiasi_piksel():
    s_x, s_y, x, y = 1, 3, 5, 8
    mask[s_y:y, s_x:x] = F_PR_FG
    print(gambar.shape)
    print(mask)

    bg_idx = np.where(np.logical_or(
        mask == F_BG, mask == F_PR_BG
    ))

    fg_idx = np.where(np.logical_or(
        mask == F_FG, mask == F_PR_FG
    ))
    
    # print('(pr_)bgd count: \n', bg_idx, '\n(pr_)fgd count: \n', fg_idx)
    print('(pr_)bgd count: ', bg_idx[1].size, '(pr_)fgd count:', fg_idx[1].size)

    print('inisiasi piksel selesai')

    return(bg_idx, fg_idx)


idx_bg, idx_fg = inisiasi_piksel()


(10, 7, 3)
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 3 3 3 3 0 0]
 [0 3 3 3 3 0 0]
 [0 3 3 3 3 0 0]
 [0 3 3 3 3 0 0]
 [0 3 3 3 3 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
(pr_)bgd count:  50 (pr_)fgd count: 20
inisiasi piksel selesai


In [11]:
print(idx_fg)

def init_assign_gmm():
    gmm_fg = GaussianMixtureModels(gambar[idx_fg])
    gmm_bg = GaussianMixtureModels(gambar[idx_bg])

    komponen_piksel[idx_fg] = gmm_fg.assign_component(gambar[idx_fg])
    komponen_piksel[idx_bg] = gmm_bg.assign_component(gambar[idx_bg])

    # gmm_bg = GaussianMixtureModels(gambar[idx_bg])
    print('Komponen piksel FG: %d, Komponen piksel BG: %d, Total komponen: %d' % (len(komponen_piksel[idx_fg]), len(komponen_piksel[idx_bg]), len(komponen_piksel)))
    print('inisiasi GMM selesai')

init_assign_gmm()

(array([3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7],
      dtype=int64), array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
      dtype=int64))
random labels selesai yaitu :
[1 4 3 0 1 0 2 1 4 4 4 0 2 0 4 0 3 3 2 3]
banyaknya labels:  20
[5. 3. 3. 4. 5.]
nilai K:  [0 1 2 3 4]
jumlah piksel untuk k = 0,1,2,3,4:  [5 3 3 4 5]
0
1
2
3
4
koefisien:  [0.25 0.15 0.15 0.2  0.25]
means:  [[149.8        188.         195.2       ]
 [151.66666667 188.33333333 195.        ]
 [148.         186.33333333 192.33333333]
 [146.25       184.5        193.        ]
 [151.4        188.8        194.2       ]]
kovarians:  [[[46.2        40.25       40.8       ]
  [40.25       36.5        40.25      ]
  [40.8        40.25       52.7       ]]

 [[42.33333333 42.16666667 29.5       ]
  [42.16666667 42.33333333 29.        ]
  [29.5        29.         21.        ]]

 [[37.         33.5        23.        ]
  [33.5        30.33333333 20.83333333]
  [23.         20.83333333 14.33333333

d:\Documents\file apis\kebutuhan kuliah\mata kuliah\smester 7\SKRIPSI\Skripsi_Hafiz\wound_gc\GMM.py:92: RuntimeWarning: overflow encountered in exp
  result = np.exp(-.5 * mult) / (np.sqrt(2 * np.pi) * np.sqrt(np.linalg.det(self.kovarians[k])))
d:\Documents\file apis\kebutuhan kuliah\mata kuliah\smester 7\SKRIPSI\Skripsi_Hafiz\wound_gc\GMM.py:92: RuntimeWarning: invalid value encountered in sqrt
  result = np.exp(-.5 * mult) / (np.sqrt(2 * np.pi) * np.sqrt(np.linalg.det(self.kovarians[k])))


LinAlgError: Singular matrix

In [ ]:
a = 9

print(a)
def tambah(x):
    x = x + 1
    print(x)

tambah(a)

print(a)


9
10
9
